### ISSUE TITLE
cert-manager operator does not show any Certificate created

### ISSUE THREAD

**Issue by dboc** [openshift/cert-manager-operator#126]
Hello,

After i changed the techpreview version to stable version(1.10.2), the list of certificate is not show anything.
Even creating new Certificate are not show any Certificate Resource, image below:

![image](https://github.com/openshift/cert-manager-operator/assets/7704278/37b3b574-8b20-45d2-978d-4419f1253b30)

But we have certificate:
```bash
$ oc get Certificate -A
NAMESPACE          NAME                             READY   SECRET                          AGE
devops             ac-webapi-cert                   True    tls-ac-webapi-cert              7m53s
devops             app01-apicertificado-dev-cert    True    tls-app01-apicertificado-cert   2d21h
devops             app01-dev-cert                   True    tls-app01-cert                  2d21h
devops             app01-devarea-dev-cert           True    tls-app01-devarea-cert          2d21h
devops             app01-html-dev-cert              True    tls-app01-html-cert             2d21h
devops             app01-jobs-dev-cert              True    tls-app01-jobs-cert             2d21h
devops             app01-motorpdf-dev-cert          True    tls-app01-motorpdf-cert         2d21h
devops             app01-webapi-dev-cert            True    tls-app01-webapi-cert           2d21h
devops             tls-app01-processjobs-dev-cert   True    tls-app01-processjobs-cert      2d21h
devops             tls-company-notificacoes         True    tls-company-notificacoes-cert   2d20h
sbx-teste-daniel   acme-app0237-staging             True    tls2-app0237-sbx                4d
```

is this correct? 
It must have to show Certificate Resource, at least to admin of operator namespace.

**Comment by swghosh** [comment]
This is a known bug as of 1.10 version of our operator, as the OpenShift Console ends up listing only the resources from the namespace where the operator is installed instead of all namespaces. As a workaround, please use OpenShift Console's API Explorer feature from where you can access all cert-manager related custom resorces (eg. Certificates, CertificateRequests, Issuers, Orders, Challenges, etc.) and view their instances across all namespaces.

For more details please check the bug report in https://issues.redhat.com/browse/OCPBUGS-11647.

**Comment by dboc** [comment]
Hello everyone,
I thinks this issue is related to this pull request:
https://github.com/openshift/cert-manager-operator/pull/121

Yet not solved
